@startuml
package "Authentication Service" {
    Rectangle "POST - register\n{\n  username: str,\n  password: str\n}" as register
    Rectangle "POST - auth\n{\n  username: str,\n  password: str\n}" as auth
    Rectangle "POST - unregister\n{\n  username: str,\n  password: str\n}" as unregister
    Rectangle "POST - verify\n{\n  username: str,\n  token: str\n}" as verify
    Rectangle "POST - logout\n{\n  username: str,\n  token: str\n}" as logout
    Rectangle "GET  - userinfo\n(\n  Authorization: hash\n)" as userinfo
}

package "Message Service" {
    Rectangle "GET  - messages\n(\n  Authorization: hash\n)" as userMsgs
    Rectangle "POST - message/<username>\n{\n  sender: userid,\n  receiver: userid,\n  token: hash,\n  message: str\n}" as sendMessage
}

package "Web Service" {
    Rectangle "Login/out page"
    Rectangle "User info page"
    Rectangle "Active users page"
    Rectangle "Send message page"
    Rectangle "List messages page"
    Rectangle "Search page"
}

package "Forum Service" {
    Rectangle "POST - /create_post" as createPost
    Rectangle "DELETE - /delete_post/<post_id>" as deletePost
    Rectangle "PUT - /edit_post/<post_id>" as editPost
    Rectangle "POST - /create_comment/<comment_id>" as createComment
    Rectangle "DELETE - /delete_comment/<comment_id>" as deleteComment
    Rectangle "PUT - /edit_comment/<comment_id>" as editComment
    Rectangle "GET - /get_all_posts" as getPosts
    Rectangle "GET - /get_all_comments" as getComments
}

database "Databases" {
    [Data:\nusers\n |username\n |hash\n |type] as users
    [Messages:\nmessages\n |sender\n |receiver\n |message\n |timestamp] as messages
    [Forums:\nposts] as posts
    [Forums:\ncomments] as comments
}

actor "Google API" as googleApi
actor "JokeAPI" as jokeApi

[Authentication Service] --> [users] : SQL
[Message Service] --> [messages] : SQL
[Message Service] --> [verify] : REST
[Web Service] --> [Forum Service]
[Web Service] --> jokeApi : REST
[Web Service] --> register : REST
[Web Service] --> auth : REST
[Web Service] --> logout : REST
[Web Service] --> userinfo : REST
[Web Service] --> unregister : REST
[Web Service] --> userMsgs : REST
[Web Service] --> sendMessage : REST
[Forum Service] --> posts : CRUD
[Forum Service] --> comments : CRUD
"Search page" --> googleApi : REST

@enduml
