apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-msg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-msg
  template:
    metadata:
      labels:
        app: flask-msg
    spec:
      volumes:
        - name: service-account-credentials-volume
          secret:
            secretName: service-account-credentials
            items:
              - key: sa_json
                path: sa_credentials.json
      containers:
      - name: flask-msg-container
        image: gcr.io/semiotic-garden-407210/mentalni-skrbnik-msg:latest
        volumeMounts:
          - name: service-account-credentials-volume
            mountPath: /etc/gcp
            readOnly: true
        env:
        - name: AUTH_HOST
          value: http://34.118.27.140:6734/
        - name: DB_UNAME
          valueFrom:
            secretKeyRef:
              name: db-user
              key: db-username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-pass
              key: db-password
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-host
              key: db-host
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/gcp/sa_credentials.json
        ports:
        - containerPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: flask-msg-service
spec:
  selector:
    app: flask-msg
  ports:
  - protocol: TCP
    port: 8573
    targetPort: 4000
  type: LoadBalancer
