apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-web
  template:
    metadata:
      labels:
        app: flask-web
    spec:
      containers:
      - name: flask-web-container
        image: gcr.io/semiotic-garden-407210/mentalni-skrbnik-web:latest
        ports:
        - containerPort: 443


---
apiVersion: v1
kind: Service
metadata:
  name: flask-web-service
spec:
  selector:
    app: flask-web
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443
  type: LoadBalancer
