apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-auth
  template:
    metadata:
      labels:
        app: flask-auth
    spec:
      volumes:
        - name: service-account-credentials-volume
          secret:
            secretName: service-account-credentials
            items:
              - key: sa_json
                path: sa_credentials.json
      containers:
      - name: flask-auth-container
        image: gcr.io/semiotic-garden-407210/mentalni-skrbnik-auth:latest
        volumeMounts:
          - name: service-account-credentials-volume
            mountPath: /etc/gcp
            readOnly: true
        env:
        - name: DB_UNAME
          valueFrom:
            secretKeyRef:
              name: db-user
              key: db-username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-pass
              key: db-password
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-host
              key: db-host
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/gcp/sa_credentials.json
        ports:
        - containerPort: 5000


---
apiVersion: v1
kind: Service
metadata:
  name: flask-auth-service
spec:
  selector:
    app: flask-auth
  ports:
  - protocol: TCP
    port: 6734
    targetPort: 5000
  type: LoadBalancer
