name: Docker Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: data
        ports:
          - 3306:3306

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: docker build auth
      run: docker build -t mentalni-skrbnik-auth:latest docker/authService

    - name: Set up user databases
      run: |
        mysql -h 127.0.0.1 -P 3306 -u root -proot_password -e "CREATE DATABASE IF NOT EXISTS data; use data; CREATE TABLE users (username VARCHAR(255) NOT NULL PRIMARY KEY, password VARCHAR(2048) NOT NULL, type VARCHAR(50));CREATE DATABASE IF NOT EXISTS messages; use messages; CREATE TABLE messages (msgID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, sender VARCHAR(255) NOT NULL, receiver VARCHAR(255) NOT NULL, timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, message TEXT NOT NULL);"    

    - name: docker build images
      run: |
        docker build -t mentalni-skrbnik-web:latest docker/webService
        docker build -t mentalni-skrbnik-msg:latest docker/msgService

    - name: Run tests
      run: |
        docker run -d -e DB_UNAME=root -e DB_PASS=root_password -e DB_HOST=172.17.0.1 mentalni-skrbnik-auth:latest
        docker run -d -e DB_UNAME=root -e DB_PASS=root_password -e DB_HOST=172.17.0.1 -e AUTH_HOST=http://172.17.0.2:5000 mentalni-skrbnik-msg:latest
        docker run -v ${PWD}/test:/test mentalni-skrbnik-auth:latest sh -c "sleep 1 && python /test/testAuth.py"
        docker run -v ${PWD}/test:/test mentalni-skrbnik-msg:latest sh -c "sleep 1 && python /test/testMsg.py"
